name: lat_lon_grid_plugin
description: Adds a latitude / longitude grid as plugin to the [flutter_map](https://github.com/fleaflet/flutter_map/).
version: 0.2.0
homepage: https://github.com/mat8854/
repository: https://github.com/mat8854/lat_lon_grid_plugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: '>=0.13.0'
  latlong2: '>=0.8.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
