name: lat_lon_grid_plugin
description: Adds a latitude / longitude grid as plugin to the [flutter_map](https://github.com/johnpryan/flutter_map/).
version: 0.0.1
homepage: https://github.com/mat8854/
repository: https://github.com/mat8854/lat_lon_grid_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.8.2
  latlong: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter



